inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Include
    - Exclude
    - AllowedPatterns
plugins:
  - rubocop-rspec
    #- rubocop-rails
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'front/node_modules/**/*'

Naming/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
