inherit_mode:
  merge:
    - Include
    - Exclude
    - AllowedPatterns
plugins:
  - rubocop-rspec
    #- rubocop-rails
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'front/node_modules/**/*'

Naming/VariableNumber:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

# RSpec configuration
RSpec/ContextWording:
  AllowedPatterns: ['の場合', 'する場合', 'しない場合', 'がない場合', 'がある場合', 'になった場合', 'でない場合', 'を.*する場合', 'を.*しない場合', 'がいない場合', 'がいる場合', '.*を行う場合']

RSpec/ExampleLength:
  Max: 26

RSpec/MultipleExpectations:
  Max: 8

RSpec/MultipleMemoizedHelpers:
  Max: 13

RSpec/NestedGroups:
  Max: 5

RSpec/InstanceVariable:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
