name: Build

#プルリクエスト作成時に実行(他にもpush時など設定できます)
on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rspec_job:
    #ubuntu環境で動かします
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.2-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    #GitHub Actionsでサポートしているrubyのversionは2.6系以降です
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby version
        uses: ruby/setup-ruby@master
        with:
          ruby-version: 3.2.0

      #MySQLをインストール
      #- name: Install dependent libralies
      #  run: sudo apt-get install libmysqlclient-dev

      - name: Setup bundler
        run: gem install bundler

      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: rubocop
        run: bundle exec rubocop
      - name: tmp cache clear
        run: bundle exec rails tmp:cache:clear

      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

      - name: Run RSpec
        run: bundle exec rspec
        env:
          TZ: "Asia/Tokyo" # タイムゾーンを指定
          LANG: "ja_JP.UTF-8"
          LC_ALL: "C.UTF-8"
          LANGUAGE: "ja_JP.UTF-8"
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          BASE_URL: 'http://localhost:3000'
      # working-directory: ./api
      # - name: Codecov
      #   uses: codecov/codecov-action@v2.1.0
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: coverage # このディレクトリに、テスティングツールによるカバレッジレポートファイルが出力される想定
